// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8pY3LYpg43DsWIEf4L4MBpdCVMj2qX4Q',
    appId: '1:46437057409:web:528f8678be71be0ede9e80',
    messagingSenderId: '46437057409',
    projectId: 'chat-app-5065c',
    authDomain: 'chat-app-5065c.firebaseapp.com',
    storageBucket: 'chat-app-5065c.appspot.com',
    measurementId: 'G-0113VV2WQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTn7IhoGr3CMbmKgB4SRxw4sff8qG1Ww',
    appId: '1:46437057409:android:9453296cca2b6276de9e80',
    messagingSenderId: '46437057409',
    projectId: 'chat-app-5065c',
    storageBucket: 'chat-app-5065c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoirjIFuJYNhsSam7Tm-wbItt25_v-4Q',
    appId: '1:46437057409:ios:6b382e3029f375f7de9e80',
    messagingSenderId: '46437057409',
    projectId: 'chat-app-5065c',
    storageBucket: 'chat-app-5065c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoirjIFuJYNhsSam7Tm-wbItt25_v-4Q',
    appId: '1:46437057409:ios:6b382e3029f375f7de9e80',
    messagingSenderId: '46437057409',
    projectId: 'chat-app-5065c',
    storageBucket: 'chat-app-5065c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8pY3LYpg43DsWIEf4L4MBpdCVMj2qX4Q',
    appId: '1:46437057409:web:16502654e4674ec3de9e80',
    messagingSenderId: '46437057409',
    projectId: 'chat-app-5065c',
    authDomain: 'chat-app-5065c.firebaseapp.com',
    storageBucket: 'chat-app-5065c.appspot.com',
    measurementId: 'G-NPSBY78KM3',
  );
}
